# How many infants are anaemic in india 

**Dataset:** RBI Handbook of Statistics on Indian States

In [1]:
pip install pandas

Requirement already satisfied: pandas in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.0.5)
Requirement already satisfied: numpy>=2.3.3 in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in .\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in .\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

In [3]:
df = pd.read_excel('Rbi_Data_ANAEMIA.xlsx')

In [4]:
df.head(9)

,State/Union Territory,NFHS 3 (2005-06),NFHS 4 (2015-16),NFHS 5 (2019-21)
0,Andaman & Nicobar Islands,-,49,40
1,Andhra Pradesh,70.8,58.6,63.2
2,Arunachal Pradesh,56.9,50.7,56.6
3,Assam,69.6,35.7,68.4
4,Bihar,78,63.5,69.4
5,Chandigarh,-,73.1,54.6
6,Chhattisgarh,71.2,41.6,67.2
7,Dadra & Nagar Haveli,-,84.6,75.8#
8,Daman & Diu,-,73.8,-

In [5]:
df.tail(5)

   State/Union Territory NFHS 3 (2005-06) NFHS 4 (2015-16) NFHS 5 (2019-21)
33               Tripura             62.9             48.3             64.2
34         Uttar Pradesh             73.9             63.2             66.4
35           Uttarakhand             61.4             59.8             58.8
36           West Bengal               61             54.2               69
37             ALL INDIA             69.5             58.4             67.1

In [6]:
df.shape

(38, 4)

In [7]:
df.columns

Index(['State/Union Territory', 'NFHS 3 (2005-06)', 'NFHS 4 (2015-16)',
       'NFHS 5 (2019-21)'],
      dtype='str')

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 38 entries, 0 to 37
Data columns (total 4 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   State/Union Territory  38 non-null     str
 1   NFHS 3 (2005-06)       38 non-null     object
 2   NFHS 4 (2015-16)       38 non-null     object
 3   NFHS 5 (2019-21)       38 non-null     object
dtypes: object(3), str(1)
memory usage: 1.3+ KB

In [9]:
df.sort_values(by=['NFHS 4 (2015-16)', 'NFHS 5 (2019-21)'], ascending=True).head(5)

   State/Union Territory NFHS 3 (2005-06) NFHS 4 (2015-16) NFHS 5 (2019-21)
24               Mizoram             44.2             17.7             46.4
25              Nagaland                -             21.6             42.7
22               Manipur             41.1             23.9             42.8
17                Kerala             44.5             35.6             39.4
3                  Assam             69.6             35.7             68.4

### I tried to find out top 5 states/union territories that were high on the index in the past two surveys by NFHS

In [10]:
df.describe()

,State/Union Territory,NFHS 3 (2005-06),NFHS 4 (2015-16),NFHS 5 (2019-21)
count,38,38,38.0,38.0
unique,38,29,35.0,37.0
top,Andaman & Nicobar Islands,-,50.7,64.2
freq,1,9,2.0,2.0

In [11]:
df["State/Union Territory"]

0     Andaman & Nicobar Islands
1                Andhra Pradesh
2             Arunachal Pradesh
3                         Assam
4                         Bihar
5                    Chandigarh
6                  Chhattisgarh
7          Dadra & Nagar Haveli
8                   Daman & Diu
9                         Delhi
10                          Goa
11                      Gujarat
12                      Haryana
13             Himachal Pradesh
14              Jammu & Kashmir
15                    Jharkhand
16                    Karnataka
17                       Kerala
18                       Ladakh
19                  Lakshadweep
20               Madhya Pradesh
21                  Maharashtra
22                      Manipur
23                    Meghalaya
24                      Mizoram
25                     Nagaland
26                       Odisha
27                   Puducherry
28                       Punjab
29                    Rajasthan
30                       Sikkim
31                   Tamil Nadu
32                    Telangana
33                      Tripura
34                Uttar Pradesh
35                  Uttarakhand
36                  West Bengal
37                    ALL INDIA
Name: State/Union Territory, dtype: str

In [12]:
df[[
    "State/Union Territory",
    "NFHS 4 (2015-16)",
    "NFHS 5 (2019-21)"
]]

        State/Union Territory NFHS 4 (2015-16) NFHS 5 (2019-21)
0   Andaman & Nicobar Islands               49               40
1              Andhra Pradesh             58.6             63.2
2           Arunachal Pradesh             50.7             56.6
3                       Assam             35.7             68.4
4                       Bihar             63.5             69.4
5                  Chandigarh             73.1             54.6
6                Chhattisgarh             41.6             67.2
7        Dadra & Nagar Haveli             84.6            75.8#
8                 Daman & Diu             73.8                -
9                       Delhi             62.6             69.2
10                        Goa             48.3             53.2
11                    Gujarat             62.6             79.7
12                    Haryana             71.7             70.4
13           Himachal Pradesh             53.7             55.4
14            Jammu & Kashmir             43.3             72.7
15                  Jharkhand             69.9             67.4
16                  Karnataka             60.9             65.5
17                     Kerala             35.6             39.4
18                     Ladakh                -             93.9
19                Lakshadweep             51.9             43.1
20             Madhya Pradesh             68.9             72.6
21                Maharashtra             53.8             68.9
22                    Manipur             23.9             42.8
23                  Meghalaya               48             45.1
24                    Mizoram             17.7             46.4
25                   Nagaland             21.6             42.7
26                     Odisha             44.6             64.2
27                 Puducherry             44.9               64
28                     Punjab             56.6             71.1
29                  Rajasthan             60.3             71.5
30                     Sikkim             55.1             56.4
31                 Tamil Nadu             50.7             57.4
32                  Telangana             60.7               70
33                    Tripura             48.3             64.2
34              Uttar Pradesh             63.2             66.4
35                Uttarakhand             59.8             58.8
36                West Bengal             54.2               69
37                  ALL INDIA             58.4             67.1

In [13]:
df[df["State/Union Territory"] == "Goa"]

   State/Union Territory NFHS 3 (2005-06) NFHS 4 (2015-16) NFHS 5 (2019-21)
10                   Goa             38.2             48.3             53.2

# Tried finding out for a particular state.